name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: kubectl-simple
        uses: steebchen/kubectl@v2.0.0
        with:
          config:
            ${{ secrets.KUBECTL_CONFIG }}
          command:
            get po
